### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by anarche0** [Ubalube/src#3]
**Describe the bug**
I have vanilla fix installed with other small mod and when I went to use your mod the message pops up saying that my world could get corrupted but the game didn't crash. (Must be vanilla fix) Is there a way to not have this happen or something?

**Version**
1.0

**Forge**
Forge 14.23.5.2838

**Additional Information**
https://paste.dimdev.org/ifadifayam.mccrash

**Comment by anarche0** [comment]
The mod version I downloaded says 1.1 but this says 1.0 for whatever reason.
![diamond](https://user-images.githubusercontent.com/33385769/60032554-d24ac900-9674-11e9-8688-da51a3abf949.PNG)

**Comment by Ubalube** [comment]
Can you tell me what the other mods are?

**Comment by Ubalube** [comment]
This issue has been resolved in Diamond Caliber 3.0+
