### ISSUE TITLE
Crash by click on the messae to version 2.0

### ISSUE THREAD

**Issue by Titoo8899** [Ubalube/src#5]
Her is the Bugreport:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Players List Core Plugin (oxygen-players-list-1.12.2-0.9.1.jar)
  FMLModule (mdxlib-3.0.0.20.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  FirstAid CoreMod (firstaid-core-1.6.3.jar)
  Oxygen Core Plugin (oxygen-core-1.12.2-0.9.6.jar)
  EmojicordCorePlugin (Emojicord-1.12.2-1.0.2.15-universal.jar)
  McLib core mod (mclib-1.0.3-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 12/7/19 4:35 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177070_b(RenderLivingBase.java:488)
	at net.minecraft.client.renderer.entity.RenderLightmap.canRenderNamePlate(Unknown Source)
	at mchorse.emoticons.c84e7f0de5b37b7cd.mc71d19b82226ce90(Unknown Source)
	at mchorse.emoticons.c1ab60acf71f23163.m9d06d98d8c7bd1ea(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_368_c1ab60acf71f23163_m9d06d98d8c7bd1ea_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at com.ubalube.scifiaddon.client.mainmenu.utilities.FakePlayerRendering.renderPlayerModel(FakePlayerRendering.java:115)
	at com.ubalube.scifiaddon.client.mainmenu.utilities.GuiRenderHelper.renderPlayer(GuiRenderHelper.java:362)
	at com.ubalube.scifiaddon.client.mainmenu.GuiCaliberMenu.func_73863_a(GuiCaliberMenu.java:85)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177070_b(RenderLivingBase.java:488)
	at net.minecraft.client.renderer.entity.RenderLightmap.canRenderNamePlate(Unknown Source)
	at mchorse.emoticons.c84e7f0de5b37b7cd.mc71d19b82226ce90(Unknown Source)
	at mchorse.emoticons.c1ab60acf71f23163.m9d06d98d8c7bd1ea(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_368_c1ab60acf71f23163_m9d06d98d8c7bd1ea_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at com.ubalube.scifiaddon.client.mainmenu.utilities.FakePlayerRendering.renderPlayerModel(FakePlayerRendering.java:115)
	at com.ubalube.scifiaddon.client.mainmenu.utilities.GuiRenderHelper.renderPlayer(GuiRenderHelper.java:362)
	at com.ubalube.scifiaddon.client.mainmenu.GuiCaliberMenu.func_73863_a(GuiCaliberMenu.java:85)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: com.ubalube.scifiaddon.client.mainmenu.GuiCaliberMenu
	Mouse location: Scaled: (190, 214). Absolute: (381, 50)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2391768184 bytes (2280 MB) / 3892314112 bytes (3712 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 59 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version               | Source                                            | Signature                                |
	|:------ |:-------------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft            | 1.12.2                | minecraft.jar                                     | None                                     |
	| UCHIJA | mcp                  | 9.42                  | minecraft.jar                                     | None                                     |
	| UCHIJA | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                | 14.23.5.2768          | forge-1.12.2-14.23.5.2768.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | firstaidcore         | 1.0.0                 | minecraft.jar                                     | None                                     |
	| UCHIJA | asphaltmod           | 2.2.0                 | AsphaltMod2.2.0-18_forge-1.12.2-14.23.5.2768.jar  | None                                     |
	| UCHIJA | better_diving        | 1.4.13                | BetterDiving-1.12.2-1.4.13.jar                    | None                                     |
	| UCHIJA | bookshelf            | 2.3.588               | Bookshelf-1.12.2-2.3.588.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | birdwmod             | 1.12.2-1.0.0          | TheBirdwatchingMod-1.5.0.jar                      | None                                     |
	| UCHIJA | bookworm             | 1.12.2-2.3.0          | bookworm-1.12.2-2.3.0.jar                         | None                                     |
	| UCHIJA | capsule              | 1.12.2-3.2.103        | Capsule-1.12.2-3.2.103.jar                        | None                                     |
	| UCHIJA | communism            | 1.1                   | communism-1.1.2.jar                               | None                                     |
	| UCHIJA | craftstudioapi       | 1.0.0                 | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
	| UCHIJA | caliber              | 2.0                   | diamond-caliber-2.0.jar                           | None                                     |
	| UCHIJA | fantasticlib         | 1.12.2.029            | FantasticLib-1.12.2.029.jar                       | None                                     |
	| UCHIJA | dynamicstealth       | 1.12.2.097            | DynamicStealth-1.12.2.097.jar                     | None                                     |
	| UCHIJA | emojicord            | 1.0.2.15              | Emojicord-1.12.2-1.0.2.15-universal.jar           | None                                     |
	| UCHIJA | mclib                | 1.0.3                 | mclib-1.0.3-1.12.2.jar                            | None                                     |
	| UCHIJA | emoticons            | 0.3.2                 | emoticons-0.3.2-1.12.2.jar                        | None                                     |
	| UCHIJA | fcl                  | 1.XII.49              | Fexcraft+Common+Library-1.XII.49.jar              | None                                     |
	| UCHIJA | tmt                  | 1.4                   | Fexcraft+Common+Library-1.XII.49.jar              | None                                     |
	| UCHIJA | forgelin             | 1.8.4                 | Forgelin-1.8.4.jar                                | None                                     |
	| UCHIJA | fsmm                 | 2.3.1                 | FSMM-2.3.1-1.12.x.jar                             | None                                     |
	| UCHIJA | ftblib               | 5.4.4.5               | FTBLib-5.4.4.5.jar                                | None                                     |
	| UCHIJA | ftbguides            | 2.0.0.52              | FTBGuides-2.0.0.52.jar                            | None                                     |
	| UCHIJA | ftbutilities         | 5.4.0.123             | FTBUtilities-5.4.0.123.jar                        | None                                     |
	| UCHIJA | itemfilters          | 1.0.3.12              | ItemFilters-1.0.3.12.jar                          | None                                     |
	| UCHIJA | ftbquests            | 1.8.0.237             | FTBQuests-1.8.0.237.jar                           | None                                     |
	| UCHIJA | ftbmoney             | 1.1.0.42              | FTBMoney-1.1.0.42.jar                             | None                                     |
	| UCHIJA | ftbbackups           | 0.0.0.ftbbackups      | FTBUtilitiesBackups-1.0.0.4.jar                   | None                                     |
	| UCHIJA | grandeconomy         | 1.2.1                 | GrandEconomy-1.12.2-1.2.1.jar                     | None                                     |
	| UCHIJA | holdyerbreath        | 1.12.2-1.1.2          | holdyerbreath-1.12.2-1.1.2.jar                    | None                                     |
	| UCHIJA | mdxlib               | 3.0.0.20              | mdxlib-3.0.0.20.jar                               | None                                     |
	| UCHIJA | lbm                  | 1.0                   | lbm-1.0.0.9.jar                                   | None                                     |
	| UCHIJA | letsencryptcraft     | @VERSION@             | letsencryptcraft-1.10.2-1.2.0.jar                 | None                                     |
	| UCHIJA | mcwroofs             | 1.0                   | mcw-roofs-1.0.0-mc1.12.2.jar                      | None                                     |
	| UCHIJA | oxygen_core          | 0.9.6                 | oxygen-core-1.12.2-0.9.6.jar                      | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_cp_fsmm       | 0.9.0                 | oxygen-cp-fsmm-1.12.2-0.9.0.jar                   | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_exchange      | 0.9.0                 | oxygen-exchange-1.12.2-0.9.0.jar                  | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_friendslist   | 0.9.1                 | oxygen-friends-list-1.12.2-0.9.1.jar              | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_groups        | 0.9.1                 | oxygen-groups-1.12.2-0.9.1.jar                    | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_interaction   | 0.9.0                 | oxygen-interaction-1.12.2-0.9.0.jar               | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_mail          | 0.9.0                 | oxygen-mail-1.12.2-0.9.0.jar                      | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_menu          | 0.9.0                 | oxygen-menu-1.12.2-0.9.0.jar                      | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_merchants     | 0.9.2                 | oxygen-merchants-1.12.2-0.9.2.jar                 | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_playerslist   | 0.9.1                 | oxygen-players-list-1.12.2-0.9.1.jar              | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_teleportation | 0.9.1                 | oxygen-teleportation-1.12.2-0.9.1.jar             | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | oxygen_trade         | 0.9.1                 | oxygen-trade-1.12.2-0.9.1.jar                     | 503a793335572ddd78512349bd8048f536a62fdb |
	| UCHIJA | smm                  | 1.12.2-0.4            | ScrollableMainMenu-1.12.2-0.4.jar                 | None                                     |
	| UCHIJA | resourceloader       | 1.5.3                 | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | smoothzoom           | 1.0                   | Smooth+Zoom-1.0.jar                               | None                                     |
	| UCHIJA | stadiumcraft         | 1.0.0                 | StadiumCraft 1.12.2 Version 1.jar                 | None                                     |
	| UCHIJA | staminaplus          | 1.2                   | staminaplus-1.1.1.jar                             | None                                     |
	| UCHIJA | tektopia             | 1.1.0                 | tektopia-1.1.0.jar                                | None                                     |
	| UCHIJA | tektopiainformation  | 1.4.0                 | TektopiaInformation-1.12.2-1.1.0-1.4.0.jar        | None                                     |
	| UCHIJA | worldedit            | 6.1.10-SNAPSHOT       | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
	| UCHIJA | firstaid             | 1.6.3                 | firstaid-1.6.3.jar                                | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| UCHIJA | nofog                | 1.12.2-1.12.2-1.0.3.0 | NoFog-1.12.2b3.jar                                | 0bf221d944c89aaf3ccb7b8315148f222be50739 |
	| UD     | mclib_core           | 1.0.3                 | minecraft.jar                                     | None                                     |

	Loaded coremods (and transformers): 
Players List Core Plugin (oxygen-players-list-1.12.2-0.9.1.jar)
  austeretony.oxygen_playerslist.common.core.PlayersListClassTransformer
FMLModule (mdxlib-3.0.0.20.jar)
  com.asx.mdx.AccessTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
FirstAid CoreMod (firstaid-core-1.6.3.jar)
  ichttt.mods.firstaid.common.asm.PotionTransformer
Oxygen Core Plugin (oxygen-core-1.12.2-0.9.6.jar)
  austeretony.oxygen_core.common.core.plugin.OxygenClassTransformer
EmojicordCorePlugin (Emojicord-1.12.2-1.0.2.15-universal.jar)
  net.teamfruit.emojicord.asm.EmojicordTransformer
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3308' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3308, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

**Comment by Ubalube** [comment]
Try using only Diamond Caliber and see if it works. Remove all mods temporarily, it may be a compatibility issue.

**Comment by PROTOTYPEthe1st** [comment]
I have the same issue. I uninstalled everything except for D-Cal and it seemed to work fine. The part of the code where it says Render Screen mad me think that maybe it was an issue with the main menu. I have mods that change the main menu, and looking at the error above so does the OP. The only problem is that in the config file for D-Cal, the main menu enable/disable option does not work. This seems to be the issue for me anyway.

**Comment by Ubalube** [comment]
Ill fix this in the next update!

**Comment by Ubalube** [comment]
This issue has been resolved in Diamond Caliber 3.0+
