### ISSUE TITLE
A crash at startup

### ISSUE THREAD

**Issue by doctor-something5000** [Ubalube/src#6]
there's a crash at startup which prevents me from going further.
here's a link [https://paste.dimdev.org/ayironiqic.sql](https://paste.dimdev.org/ayironiqic.sql)

**Comment by thecrescentkid** [comment]
https://paste.dimdev.org/eseyagemeh.mccrash

**Comment by Ubalube** [comment]
The link is invalid but I assume it is because of the main menu. This has been resolved in Diamond Caliber 3.0+

**Comment by Ubalube** [comment]
The link is invalid but I assume it is because of the main menu. This has been resolved in Diamond Caliber 3.0+
