### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thecrescentkid** [Ubalube/src#7]
**Describe the bug**
the custom main menu 
still shows up even when disabled in the config.
**Version**
Diamond Caliber 2.0

**Forge**
14.23.5.2847
**Additional Information**
if you disable the custom main menu and install industrial forgoing, vanillafix  show the are conflicting, but you can return to the main menu and the mod work together fine but the main menu has a white bar on the left side and enter the mods select, and it disappears.

**Comment by Ubalube** [comment]
This has been resolved in the newest update

**Comment by Ubalube** [comment]
This has been resolved in Diamond Caliber 3.0
